#!/bin/bash

MODULE_PATH="./node_modules"
COMPILER_PATH="$MODULE_PATH/.bin/electron-compile"
PACKAGER_PATH="$MODULE_PATH/.bin/electron-packager"
PREBUILT_PATH="$MODULE_PATH/electron-prebuilt"
PREBUILT_PACKAGE_JSON_PATH="$PREBUILT_PATH/package.json"
PACKAGE_JSON_PATH="package.json"

PATH_TO_COMPILE="./src"
COMPILE_CACHE_PATH="./compile-cache"
BUILD_OUTPUT_PATH="./release"

IGNORE_PATHS="$MODULE_PATH/electron-compile/node_modules/electron-compilers|$MODULE_PATH/\\.bin"

function json_value {
  # From https://gist.github.com/cjus/1047794
  cat $1 | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $2 | tr ": " " "
}

ELECTRON_VERSION=($( json_value $PREBUILT_PACKAGE_JSON_PATH "version" ))
ELECTRON_VERSION=${ELECTRON_VERSION[1]}

APP_NAME=($( json_value $PACKAGE_JSON_PATH "appName" ))
APP_NAME=${APP_NAME[1]}

echo "Building $APP_NAME"
$COMPILER_PATH --target "$COMPILE_CACHE_PATH" "$PATH_TO_COMPILE"
$PACKAGER_PATH ./ $APP_NAME --overwrite --platform darwin --arch x64 --version "$ELECTRON_VERSION" --ignore "$IGNORE_PATHS" --out "$BUILD_OUTPUT_PATH" $@
